package hwr.csa.watchclock.modell;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.time.LocalTime;

@Entity
public class Zeiteintrag {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private long id;

    private LocalTime beginnZeit;

    private LocalTime endeZeit;

    private String kommentar;

    public Zeiteintrag(){

    }
// ID nicht Teil des Konstruktors, da AutoGenerated
    public Zeiteintrag(LocalTime beginnZeit, LocalTime endeZeit, String kommentar){
        this.beginnZeit = beginnZeit;
        this.endeZeit = endeZeit;
        this.kommentar = kommentar;
    }

    public long getId() {
        return id;
    }

    public LocalTime getBeginnZeit() {
        return beginnZeit;
    }

    public LocalTime getEndeZeit() {
        return endeZeit;
    }

    public String getKommentar() {
        return kommentar;
    }
// auskommentiert, da wert automatisch generiert wird, sollte nicht verändert werden
    /*public void setId(Integer id) {
        this.id = id;
    }*/

    public void setBeginnZeit(LocalTime beginnZeit) {
        this.beginnZeit = beginnZeit;
    }

    public void setEndeZeit(LocalTime endeZeit) {
        this.endeZeit = endeZeit;
    }

    public void setKommentar(String kommentar) {
        this.kommentar = kommentar;
    }
}
